CREATE TABLE `file_items` (
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
	`parent_id` INT UNSIGNED NOT NULL ,
	`name` VARCHAR( 255 ) NOT NULL ,
	`type` INT NOT NULL
) ENGINE = MYISAM ;

CREATE TABLE `block_items` (
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
	`parent_id` INT UNSIGNED NOT NULL ,
	`file_id` INT UNSIGNED NOT NULL ,
	`title` TEXT NOT NULL ,
	`text` TEXT NOT NULL ,
	`example` TEXT NOT NULL
) ENGINE = MYISAM ;

CREATE TABLE `note_items` (
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
	`block_id` INT UNSIGNED NOT NULL ,
	`name` VARCHAR( 255 ) NOT NULL ,
	`description` VARCHAR( 255 ) NOT NULL
) ENGINE = MYISAM ;
